const Types = {
  ADD_PIZZA: 'ADD_PIZZA',
  REMOVE_PIZZA: 'REMOVE_PIZZA',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEMS: 'CLEAR_ITEMS',
  SET_PIZZAS: 'SET_PIZZAS',
  SET_LOADED: 'SET_LOADED',
  SET_SORT_BY: 'SET_SORT_BY',
  SET_CATEGORY: 'SET_CATEGORY',
};

export default Types;
